package by.chat.core.exception;

public enum UserException {
    SUCCESS,
    EMPTY_LOGIN_ERROR,
    USER_EXIST,
    EMPTY_PASSWORD_ERROR,
    PASSWORDS_MATCH_ERROR,
    EMPTY_FIRSTNAME_ERROR,
    EMPTY_LASTNAME_ERROR,
    EMPTY_MIDDLENAME_ERROR,
    EMPTY_BIRTHDAY_ERROR,
}
